CREATE TABLE PUBLISHER ("ID" INTEGER PRIMARY KEY, "NAME" VARCHAR(100) NOT NULL )
CREATE TABLE AUTHOR ("ID" INTEGER PRIMARY KEY, "FIRST_NAME" VARCHAR(80) NOT NULL, "LAST_NAME" VARCHAR(50) NOT NULL)
CREATE TABLE BOOKS ("ID" INTEGER PRIMARY KEY, "BOOK_NAME" VARCHAR(100) NOT NULL, "PUBLISHER_ID" INTEGER NOT NULL, "AUTHOR_ID" INTEGER NOT NULL, "PRICE" FLOAT NOT NULL, "STOCK" INTEGER NOT NULL )

ALTER TABLE BOOKS ADD CONSTRAINT BOOK_PUBLISHER_ID FOREIGN KEY("PUBLISHER_ID") REFERENCES PUBLISHER ("ID")
ALTER TABLE BOOKS ADD CONSTRAINT BOOK_AUTHOR_ID FOREIGN KEY("AUTHOR_ID") REFERENCES AUTHOR ("ID")