INSERT INTO PUBLISHER("ID","NAME") VALUES (1,'Westland Press')
INSERT INTO PUBLISHER("ID","NAME") VALUES (2,'Westland Ltd')

INSERT INTO AUTHOR("ID","FIRST_NAME","LAST_NAME") VALUES(1,'Amish','Tripathi')
INSERT INTO AUTHOR("ID","FIRST_NAME","LAST_NAME") VALUES(2,'Ashwin','Sanghi')
 
INSERT INTO BOOKS("ID","BOOK_NAME","PUBLISHER_ID","AUTHOR_ID","PRICE") VALUES (1,'The Immortals of Meluha',1,1,179.0)
INSERT INTO BOOKS("ID","BOOK_NAME","PUBLISHER_ID","AUTHOR_ID","PRICE") VALUES (2,'The Secret of the Nagas',1,1,130.0)
INSERT INTO BOOKS("ID","BOOK_NAME","PUBLISHER_ID","AUTHOR_ID","PRICE") VALUES (3,'The Oath of the Vayuputras',1,1,140.0)
INSERT INTO BOOKS("ID","BOOK_NAME","PUBLISHER_ID","AUTHOR_ID","PRICE") VALUES (4,'Scion of Ikshvaku',1,1,250.0)
INSERT INTO BOOKS("ID","BOOK_NAME","PUBLISHER_ID","AUTHOR_ID","PRICE") VALUES (5,'Chanakyas Chant',2,2,230.0)
INSERT INTO BOOKS("ID","BOOK_NAME","PUBLISHER_ID","AUTHOR_ID","PRICE") VALUES (6,'The Rozabal Line',2,2,175.2)
INSERT INTO BOOKS("ID","BOOK_NAME","PUBLISHER_ID","AUTHOR_ID","PRICE") VALUES (7,'The Krishna Key',2,2,255.5)