INSERT INTO PUBLISHER("ID","NAME") VALUES (1,"Westland Press")
INSERT INTO AUTHOR("ID","FIRST_NAME","LAST_NAME") VALUES(1,"Amish","Tripathi")
INSERT INTO BOOKS("ID","BOOK_NAME","PUBLISHER_ID") VALUES (1,"The Immortals of Meluha",1)